# Este arquivo é apenas para referência de desenvolvimento local
# Para o teste prático, use o RabbitMQ remoto em amqp://137.131.204.96:5672

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pedidos-rabbitmq-local
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=vrsoftware
      - RABBITMQ_DEFAULT_PASS=6uOVxR6dy1H7Zqfz
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    name: pedidos-rabbitmq-data
